CREATE TABLE techlabuser
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR(255),
    name       VARCHAR(255),
    avatar_url VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_techlabuser PRIMARY KEY (id)
);

ALTER TABLE techlabuser
    ADD CONSTRAINT uc_techlabuser_email UNIQUE (email);