-- Criação da tabela de usuários
CREATE TABLE techlabuser
(
    id         NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email      VARCHAR2(255),
    name       VARCHAR2(255),
    avatar_url VARCHAR2(255),
    password   VARCHAR2(255),
    CONSTRAINT pk_techlabuser PRIMARY KEY (id)
);

ALTER TABLE techlabuser
    ADD CONSTRAINT uc_techlabuser_email UNIQUE (email);

