-- Criação da tabela de dispositivos IoT
CREATE TABLE iot (
    id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ativo        NUMBER(1) NOT NULL,
    bateria      NUMBER(10),
    coordenada_x VARCHAR2(255) NOT NULL,
    coordenada_y VARCHAR2(255) NOT NULL
);

