-- Criação da tabela de motos com relacionamentos
CREATE TABLE moto (
    id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    modelo       VARCHAR2(255) NOT NULL,
    placa        VARCHAR2(255) NOT NULL UNIQUE,
    data_entrada TIMESTAMP NOT NULL,
    data_saida   TIMESTAMP,
    iot_id       NUMBER(19),
    patio_id     NUMBER(19),
    CONSTRAINT fk_moto_iot FOREIGN KEY (iot_id) REFERENCES iot(id),
    CONSTRAINT fk_moto_patio FOREIGN KEY (patio_id) REFERENCES patio(id)
);

-- Índices para melhorar performance das consultas
CREATE INDEX idx_moto_iot_id ON moto(iot_id);
CREATE INDEX idx_moto_patio_id ON moto(patio_id);

